# all artifacts here must be cross OS
# for OS centric artifacts use the file "var/{os_distribution}"

base:
  - alacritty
  - fzf
  - htop
  - ncdu
  - ntfs-3g
  - pass
  - powertop
  - ranger
  - renameutils
  - ripgrep
  - testdisk
  - tldr
  - tmux
  - tree
  - zsh

base_snap:
  - speed-test
  # vtop is not available in apt neither snap package managers (try using npm instead)
  # - vtop

base_yarn:
  - chalk
  - http-server
  - json-server
  - wikit

communication:
  - telegram-desktop

desktop_omyzsh_plugins:
  - https://github.com/zsh-users/zsh-autosuggestions
  - https://github.com/zsh-users/zsh-syntax-highlighting
  - https://github.com/djui/alias-tips

development_apps:
  - docker
  - docker-compose
  - jq

development_asdf_plugins:
  - bat
  - java
  - maven
  - neovim
  - nodejs
  - ruby
  - yarn

editors:
  - vim

multimedia_apps:
  - flameshot
  - gimp
  - peek

multimedia_fonts_url:
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
  - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete.ttf
  - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Mono.ttf

multimedia_plexmediaserver_plugins:
  - https://github.com/pannal/Sub-Zero.bundle/releases/download/2.6.5.3247/Sub-Zero.bundle-2.6.5.3247.zip

network:
  - samba
