desktop_removable_files:
  - .config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml

base_distro:
  - git-extras
  - lm-sensors

browsers:
  - google-chrome-stable

network_distro:
  - openssh-server
